version: '3'
services:
  frontend5:
    container_name: daily_job_frontend5
    build: ./job-board-webapp
    ports:
      - "5174:5173"
    restart: always

  backend2:
    container_name: daily_job_backend2
    build: ./flask_backend
    ports:
      - "5001:5001"
    restart: always
